### ISSUE TITLE
How to modify the language of the map display

### ISSUE THREAD

**Issue by GINAWZF** [grumpypixel/msfs2020-gopilot#1] opened 2021-04-02 17:36 UTC
How to modify the language of the map display？Is it possible to add a language option if possible。Thank you author for developing 。

**Comment by grumpypixel** [comment] 2021-04-04 10:12
Hi ginawzf,

Thanks a lot for your message!

What language would you like your maps to be?

The problem is that OpenStreetMap (OSM) is a tile-base rendering engine, not vector-based. So the labels are part of the images. But I can see if can find other tile servers and integrate these into the application.

Best,
Sascha

**Comment by GINAWZF** [comment] 2021-04-06 00:43
> 嗨ginawzf，
> 
> 非常感谢您的留言！
> 
> 您希望地图使用哪种语言？
> 
> 问题在于OpenStreetMap（OSM）是基于图块的渲染引擎，而不是基于矢量的渲染引擎。因此，标签是图像的一部分。但是我可以看到是否可以找到其他切片服务器并将它们集成到应用程序中。
> 
> 最好，
> 萨沙



> Hi ginawzf,
> 
> Thanks a lot for your message!
> 
> What language would you like your maps to be?
> 
> The problem is that OpenStreetMap (OSM) is a tile-base rendering engine, not vector-based. So the labels are part of the images. But I can see if can find other tile servers and integrate these into the application.
> 
> Best,
> Sascha

hi grumpypixel
         I need Chinese, but not just Chinese. for example https://cn.bing.com/maps, bingmap is free to change languages. Add the option of switching languages, Is it feasible.I don't know much about programming. You can see if it works. Thanks again

**Comment by grumpypixel** [comment] 2021-04-06 16:26
Hi ginawzf,

I will add an option to set the language for Bing maps via url parameters and I will let you know as soon as I committed the code.

Best,
Sascha

**Comment by GINAWZF** [comment] 2021-04-06 16:30
> Hi ginawzf,
> 
> I will add an option to set the language for Bing maps via url parameters and I will let you know as soon as I committed the code.
> 
> Best,
> Sascha

so cool，Thanks a lot~~~

**Comment by GINAWZF** [comment] 2021-04-07 06:02
> Hi ginawzf,
> 
> I added the option to set the culture code for Bing Maps. I'm not sure if this solves your request/issue, but I hope that this works better for you than before.
> 
> Please note that this option does not work with the other maps, of course.
> 
> Examples for simplified and traditional Chinese:
> http://localhost:8888/?default_map=BingMaps.Light&bing_culture=zh-Hans
> http://localhost:8888/?default_map=BingMaps.Light&bing_culture=zh-Hant
> 
> You can download the new release here:
> https://github.com/grumpypixel/msfs2020-gopilot/releases
> 
> You should probably get your own key for Bing Maps by the way:
> https://www.microsoft.com/en-us/maps/create-a-bing-maps-key
> 
> And then go like this:
> http://localhost:8888/?bing_key=<INSERT_YOUR_OWN_BING_KEY_HERE>&default_map=BingMaps.Light&bing_culture=zh-Hans
> 
> Best,
> Sascha
> 
> Edit:
> Bing Maps Culture Codes are listed here:
> https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes

hi Sascha grumpypixel
I tested it. Great. Thank you very much~~~

**Comment by grumpypixel** [comment] 2021-04-07 07:43
Hi ginawzf,

You're very welcome! I'm glad I could help.

Have fun!

Best,
Sascha

**Closed by grumpypixel** 2021-04-07 07:43 UTC
